[package]
name = "dooservice"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tracing-actix-web = "0.7"
env_logger = "0.11.6"
serde = { version = "1.0", features = ["derive"] }
bollard = "0.18.1"
log = "0.4.22"
mongodb = "3.1.1"
